const huntObject = [
    {
        "HUNT_NBR": "DB1500",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Beaver",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 360
    },
    {
        "HUNT_NBR": "DB1501",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Box Elder",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 920
    },
    {
        "HUNT_NBR": "DB1502",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Cache",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 820
    },
    {
        "HUNT_NBR": "DB1503",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Manti/San Rafael",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 1600
    },
    {
        "HUNT_NBR": "DB1504",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Nebo",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 900
    },
    {
        "HUNT_NBR": "DB1506",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Fillmore",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 420
    },
    {
        "HUNT_NBR": "DB1508",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Kamas",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 250
    },
    {
        "HUNT_NBR": "DB1509",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "La Sal, La Sal Mtns",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 280
    },
    {
        "HUNT_NBR": "DB1510",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Monroe",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 170
    },
    {
        "HUNT_NBR": "DB1511",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Mt Dutton",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 75
    },
    {
        "HUNT_NBR": "DB1512",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Nine Mile",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 260
    },
    {
        "HUNT_NBR": "DB1513",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "North Slope",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 460
    },
    {
        "HUNT_NBR": "DB1514",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Ogden",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 380
    },
    {
        "HUNT_NBR": "DB1515",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Oquirrh-Stansbury",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 500
    },
    {
        "HUNT_NBR": "DB1516",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Panguitch Lake",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 420
    },
    {
        "HUNT_NBR": "DB1517",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Pine Valley",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 680
    },
    {
        "HUNT_NBR": "DB1518",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Boulder/Kaiparowits",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 400
    },
    {
        "HUNT_NBR": "DB1519",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Fishlake",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 220
    },
    {
        "HUNT_NBR": "DB1520",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Thousand Lakes",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 60
    },
    {
        "HUNT_NBR": "DB1521",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "San Juan, Abajo Mtns",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 450
    },
    {
        "HUNT_NBR": "DB1522",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Vernal/Bonanza",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 300
    },
    {
        "HUNT_NBR": "DB1523",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Yellowstone",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 220
    },
    {
        "HUNT_NBR": "DB1524",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Southwest Desert",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 95
    },
    {
        "HUNT_NBR": "DB1525",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Wasatch Mtns, East",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 1000
    },
    {
        "HUNT_NBR": "DB1526",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Wasatch Mtns, West",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 1255
    },
    {
        "HUNT_NBR": "DB1527",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "West Desert, Tintic",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 160
    },
    {
        "HUNT_NBR": "DB1528",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "West Desert, West",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 90
    },
    {
        "HUNT_NBR": "DB1529",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Zion",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 660
    },
    {
        "HUNT_NBR": "DB1530",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Beaver",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 1080
    },
    {
        "HUNT_NBR": "DB1531",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Box Elder",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 2760
    },
    {
        "HUNT_NBR": "DB1532",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Cache",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 2460
    },
    {
        "HUNT_NBR": "DB1533",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Manti/San Rafael",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 4800
    },
    {
        "HUNT_NBR": "DB1534",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Nebo",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 2700
    },
    {
        "HUNT_NBR": "DB1536",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Fillmore",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 840
    },
    {
        "HUNT_NBR": "DB1538",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Kamas",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 500
    },
    {
        "HUNT_NBR": "DB1539",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "La Sal, La Sal Mtns",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 840
    },
    {
        "HUNT_NBR": "DB1540",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Monroe",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 510
    },
    {
        "HUNT_NBR": "DB1541",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Mt Dutton",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 225
    },
    {
        "HUNT_NBR": "DB1542",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Nine Mile",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 520
    },
    {
        "HUNT_NBR": "DB1543",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "North Slope",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 920
    },
    {
        "HUNT_NBR": "DB1544",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Ogden",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 1140
    },
    {
        "HUNT_NBR": "DB1545",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Oquirrh-Stansbury",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 1500
    },
    {
        "HUNT_NBR": "DB1546",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Panguitch Lake",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 840
    },
    {
        "HUNT_NBR": "DB1547",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Pine Valley",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 1360
    },
    {
        "HUNT_NBR": "DB1548",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Boulder/Kaiparowits",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 1200
    },
    {
        "HUNT_NBR": "DB1549",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Fishlake",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 440
    },
    {
        "HUNT_NBR": "DB1550",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Thousand Lakes",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 80
    },
    {
        "HUNT_NBR": "DB1551",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "San Juan, Abajo Mtns",
        "SEASON_OPEN_DATE_1": "Oct 21, 2023",
        "SEASON_CLOSE_DATE_1": "Oct 29, 2023",
        "SEASON_DATE_TEXT": "Oct 21 - Oct 29, 2023",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 1360
    },
    {
        "HUNT_NBR": "DB1552",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Vernal/Bonanza",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 500
    },
    {
        "HUNT_NBR": "DB1553",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Yellowstone",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 660
    },
    {
        "HUNT_NBR": "DB1554",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Southwest Desert",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 285
    },
    {
        "HUNT_NBR": "DB1555",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Wasatch Mtns, East",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 3000
    },
    {
        "HUNT_NBR": "DB1556",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Wasatch Mtns, West",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 3765
    },
    {
        "HUNT_NBR": "DB1557",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "West Desert, Tintic",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 480
    },
    {
        "HUNT_NBR": "DB1558",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "West Desert, West",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 270
    },
    {
        "HUNT_NBR": "DB1559",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Zion",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 1320
    },
    {
        "HUNT_NBR": "DB1560",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Beaver",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 360
    },
    {
        "HUNT_NBR": "DB1561",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Box Elder",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 920
    },
    {
        "HUNT_NBR": "DB1562",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Cache",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 820
    },
    {
        "HUNT_NBR": "DB1563",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Manti/San Rafael",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 1600
    },
    {
        "HUNT_NBR": "DB1564",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Nebo",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 900
    },
    {
        "HUNT_NBR": "DB1566",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Fillmore",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 420
    },
    {
        "HUNT_NBR": "DB1568",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Kamas",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 250
    },
    {
        "HUNT_NBR": "DB1569",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "La Sal, La Sal Mtns",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 280
    },
    {
        "HUNT_NBR": "DB1570",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Monroe",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 170
    },
    {
        "HUNT_NBR": "DB1571",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Mt Dutton",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 75
    },
    {
        "HUNT_NBR": "DB1572",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Nine Mile",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 260
    },
    {
        "HUNT_NBR": "DB1573",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "North Slope",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 460
    },
    {
        "HUNT_NBR": "DB1574",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Ogden",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 380
    },
    {
        "HUNT_NBR": "DB1575",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Oquirrh-Stansbury",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 500
    },
    {
        "HUNT_NBR": "DB1576",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Panguitch Lake",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 420
    },
    {
        "HUNT_NBR": "DB1577",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Pine Valley",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 680
    },
    {
        "HUNT_NBR": "DB1578",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Boulder/Kaiparowits",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 400
    },
    {
        "HUNT_NBR": "DB1579",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Fishlake",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 220
    },
    {
        "HUNT_NBR": "DB1580",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Thousand Lakes",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 60
    },
    {
        "HUNT_NBR": "DB1581",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "San Juan, Abajo Mtns",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 450
    },
    {
        "HUNT_NBR": "DB1582",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Vernal/Bonanza",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 200
    },
    {
        "HUNT_NBR": "DB1583",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Yellowstone",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 220
    },
    {
        "HUNT_NBR": "DB1584",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Southwest Desert",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 95
    },
    {
        "HUNT_NBR": "DB1585",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Wasatch Mtns, East",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 1000
    },
    {
        "HUNT_NBR": "DB1586",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Wasatch Mtns, West",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 1255
    },
    {
        "HUNT_NBR": "DB1587",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "West Desert, Tintic",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 160
    },
    {
        "HUNT_NBR": "DB1588",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "West Desert, West",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 90
    },
    {
        "HUNT_NBR": "DB1589",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Zion",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 660
    },
    {
        "HUNT_NBR": "DB1591",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Fillmore",
        "SEASON_OPEN_DATE_1": "Oct 9, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 13, 2024",
        "SEASON_DATE_TEXT": "Oct 9 2024 - Oct 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 420
    },
    {
        "HUNT_NBR": "DB1592",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Kamas",
        "SEASON_OPEN_DATE_1": "Oct 9, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 13, 2024",
        "SEASON_DATE_TEXT": "Oct 9 2024 - Oct 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 250
    },
    {
        "HUNT_NBR": "DB1593",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Nine Mile",
        "SEASON_OPEN_DATE_1": "Oct 9, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 13, 2024",
        "SEASON_DATE_TEXT": "Oct 9 2024 - Oct 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 260
    },
    {
        "HUNT_NBR": "DB1594",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Panguitch Lake",
        "SEASON_OPEN_DATE_1": "Oct 9, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 13, 2024",
        "SEASON_DATE_TEXT": "Oct 9 2024 - Oct 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 420
    },
    {
        "HUNT_NBR": "DB1595",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Pine Valley",
        "SEASON_OPEN_DATE_1": "Oct 9, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 13, 2024",
        "SEASON_DATE_TEXT": "Oct 9 2024 - Oct 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 680
    },
    {
        "HUNT_NBR": "DB1596",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Fishlake",
        "SEASON_OPEN_DATE_1": "Oct 9, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 13, 2024",
        "SEASON_DATE_TEXT": "Oct 9 2024 - Oct 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 220
    },
    {
        "HUNT_NBR": "DB1597",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Zion",
        "SEASON_OPEN_DATE_1": "Oct 9, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 13, 2024",
        "SEASON_DATE_TEXT": "Oct 9 2024 - Oct 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 660
    },
    {
        "HUNT_NBR": "DB1598",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "North Slope",
        "SEASON_OPEN_DATE_1": "Oct 9, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 13, 2024",
        "SEASON_DATE_TEXT": "Oct 9 2024 - Oct 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 460
    },
    {
        "HUNT_NBR": "DB1599",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Chalk Creek",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 800
    },
    {
        "HUNT_NBR": "DB1600",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Chalk Creek",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 400
    },
    {
        "HUNT_NBR": "DB1601",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Chalk Creek",
        "SEASON_OPEN_DATE_1": "Oct 9, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 13, 2024",
        "SEASON_DATE_TEXT": "Oct 9 2024 - Oct 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 400
    },
    {
        "HUNT_NBR": "DB1602",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Chalk Creek",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 400
    },
    {
        "HUNT_NBR": "DB1603",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "East Canyon",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 680
    },
    {
        "HUNT_NBR": "DB1604",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "East Canyon",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 340
    },
    {
        "HUNT_NBR": "DB1605",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "East Canyon",
        "SEASON_OPEN_DATE_1": "Oct 9, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 13, 2024",
        "SEASON_DATE_TEXT": "Oct 9 2024 - Oct 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 340
    },
    {
        "HUNT_NBR": "DB1606",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "East Canyon",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 340
    },
    {
        "HUNT_NBR": "DB1607",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Morgan-South Rich",
        "SEASON_OPEN_DATE_1": "Oct 19, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 27, 2024",
        "SEASON_DATE_TEXT": "Oct 19 2024 - Oct 27 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 560
    },
    {
        "HUNT_NBR": "DB1608",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Archery",
        "HUNT_NAME": "Morgan-South Rich",
        "SEASON_OPEN_DATE_1": "Aug 17, 2024",
        "SEASON_CLOSE_DATE_1": "Sep 13, 2024",
        "SEASON_OPEN_DATE_2": "Sep 14, 2024",
        "SEASON_CLOSE_DATE_2": "Nov 30, 2024",
        "SEASON_DATE_TEXT": "Aug 17 2024 - Sept 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 280
    },
    {
        "HUNT_NBR": "DB1609",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Any Legal Weapon",
        "HUNT_NAME": "Morgan-South Rich",
        "SEASON_OPEN_DATE_1": "Oct 9, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 13, 2024",
        "SEASON_DATE_TEXT": "Oct 9 2024 - Oct 13 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 280
    },
    {
        "HUNT_NBR": "DB1610",
        "SPECIES": "Deer",
        "GENDER": "Buck",
        "HUNT_TYPE": "General Season",
        "WEAPON": "Muzzleloader",
        "HUNT_NAME": "Morgan-South Rich",
        "SEASON_OPEN_DATE_1": "Sep 25, 2024",
        "SEASON_CLOSE_DATE_1": "Oct 3, 2024",
        "SEASON_DATE_TEXT": "Sept 25 2024 - Oct 03 2024",
        "QUOTA_RES": 0,
        "QUOTA_NRES": 0,
        "QUOTA": 280
    }
  ]
module.exports = huntObject;
